# Uncomment this line to define a global platform for your project
platform :ios, ‘9.0’
use_frameworks!

target 'FindMyFriends' do

pod 'Firebase'

end

target 'FindMyFriendsTests' do

end

target 'FindMyFriendsUITests' do

end

